/*
 * Copyright 2026 Intave
 *
 * This software is licensed under the PolyForm Perimeter License 1.0.0.
 * You may use this software for any purpose, except for providing to
 * others any product that competes with the software.
 *
 * A copy of the license is available at:
 *   https://polyformproject.org/licenses/perimeter/1.0.0/
 */

package de.jpx3.intave.module.linker.packet;

public final class PacketId {
	public enum Client {
		@Deprecated
		ALL("*"),
		ABILITIES_IN("ABILITIES"),
		ADVANCEMENTS("ADVANCEMENTS"),
		ATTACK_ENTITY("ATTACK"),
		ARM_ANIMATION("ARM_ANIMATION"),
		AUTO_RECIPE("AUTO_RECIPE"),
		BEACON("BEACON"),
		BLOCK_DIG("BLOCK_DIG"),
		BLOCK_PLACE("BLOCK_PLACE"),
		BOAT_MOVE("BOAT_MOVE"),
		B_EDIT("B_EDIT"),
		CHAT_IN("CHAT"),
		CLIENT_COMMAND("CLIENT_COMMAND"),
		CLIENT_TICK_END("CLIENT_TICK_END"),
		CLOSE_WINDOW("CLOSE_WINDOW"),
		CUSTOM_PAYLOAD_IN("CUSTOM_PAYLOAD"),
		DIFFICULTY_CHANGE("DIFFICULTY_CHANGE"),
		DIFFICULTY_LOCK("DIFFICULTY_LOCK"),
		ENCHANT_ITEM("ENCHANT_ITEM"),
		ENTITY_ACTION_IN("ENTITY_ACTION"),
		ENTITY_NBT_QUERY("ENTITY_NBT_QUERY"),
		FLYING("FLYING"),
		HELD_ITEM_SLOT_IN("HELD_ITEM_SLOT"),
		ITEM_NAME("ITEM_NAME"),
		JIGSAW_GENERATE("JIGSAW_GENERATE"),
		KEEP_ALIVE("KEEP_ALIVE"),
		LOOK("LOOK"),
		PICK_ITEM("PICK_ITEM"),
		PONG("PONG"),
		POSITION("POSITION"),
		POSITION_LOOK("POSITION_LOOK"),
		RECIPE_DISPLAYED("RECIPE_DISPLAYED"),
		RECIPE_SETTINGS("RECIPE_SETTINGS"),
		RESOURCE_PACK_STATUS("RESOURCE_PACK_STATUS"),
		SETTINGS("SETTINGS"),
		SET_COMMAND_BLOCK("SET_COMMAND_BLOCK"),
		SET_COMMAND_MINECART("SET_COMMAND_MINECART"),
		SET_CREATIVE_SLOT("SET_CREATIVE_SLOT"),
		SET_JIGSAW("SET_JIGSAW"),
		SPECTATE("SPECTATE"),
		STEER_VEHICLE("STEER_VEHICLE"),
		STRUCT("STRUCT"),
		TAB_COMPLETE_IN("TAB_COMPLETE"),
		TELEPORT_ACCEPT("TELEPORT_ACCEPT"),
		TILE_NBT_QUERY("TILE_NBT_QUERY"),
		@Deprecated
		TRANSACTION("TRANSACTION"),
		TR_SEL("TR_SEL"),
		UPDATE_SIGN("UPDATE_SIGN"),
		USE_ENTITY("USE_ENTITY"),
		USE_ITEM("USE_ITEM"),
		USE_ITEM_ON("USE_ITEM_ON"),
		VEHICLE_MOVE("VEHICLE_MOVE"),
		WINDOW_CLICK("WINDOW_CLICK"),
		;

		private final String lookupName;

		Client(String lookupName) {
			this.lookupName = lookupName;
		}

		public String lookupName() {
			return lookupName;
		}
	}

	public enum Server {
		ABILITIES_OUT("ABILITIES"),
		ADVANCEMENTS("ADVANCEMENTS"),
		@Deprecated
		ALL("*"),
		ANIMATION("ANIMATION"),
		ATTACH_ENTITY("ATTACH_ENTITY"),
		AUTO_RECIPE("AUTO_RECIPE"),
		BED("BED"),
		BLOCK_ACTION("BLOCK_ACTION"),
		BLOCK_BREAK("BLOCK_BREAK"),
		BLOCK_BREAK_ANIMATION("BLOCK_BREAK_ANIMATION"),
		BLOCK_CHANGE("BLOCK_CHANGE"),
		BLOCK_CHANGED_ACK("BLOCK_CHANGED_ACK"),
		BOSS("BOSS"),
		CAMERA("CAMERA"),
		CHAT_OUT("CHAT"),
		CLOSE_WINDOW("CLOSE_WINDOW"),
		COLLECT("COLLECT"),
		COMBAT_EVENT("COMBAT_EVENT"),
		COMMANDS("COMMANDS"),
		CRAFT_PROGRESS_BAR("CRAFT_PROGRESS_BAR"),
		CUSTOM_PAYLOAD_OUT("CUSTOM_PAYLOAD"),
		CUSTOM_SOUND_EFFECT("CUSTOM_SOUND_EFFECT"),
		ENTITY("ENTITY"),
		ENTITY_DESTROY("ENTITY_DESTROY"),
		ENTITY_EFFECT("ENTITY_EFFECT"),
		ENTITY_EQUIPMENT("ENTITY_EQUIPMENT"),
		ENTITY_HEAD_ROTATION("ENTITY_HEAD_ROTATION"),
		ENTITY_LOOK("ENTITY_LOOK"),
		ENTITY_METADATA("ENTITY_METADATA"),
		ENTITY_MOVE_LOOK("ENTITY_MOVE_LOOK"),
		ENTITY_POSITION_SYNC("ENTITY_POSITION_SYNC"),
		ENTITY_SOUND("ENTITY_SOUND"),
		ENTITY_STATUS("ENTITY_STATUS"),
		ENTITY_TELEPORT("ENTITY_TELEPORT"),
		ENTITY_VELOCITY("ENTITY_VELOCITY"),
		EXPERIENCE("EXPERIENCE"),
		EXPLOSION("EXPLOSION"),
		GAME_STATE_CHANGE("GAME_STATE_CHANGE"),
		HELD_ITEM_SLOT_OUT("HELD_ITEM_SLOT"),
		INITIALIZE_BORDER("INITIALIZE_BORDER"),
		KEEP_ALIVE("KEEP_ALIVE"),
		KICK_DISCONNECT("KICK_DISCONNECT"),
		LIGHT_UPDATE("LIGHT_UPDATE"),
		LOGIN("LOGIN"),
		LOOK_AT("LOOK_AT"),
		MAP("MAP"),
		MAP_CHUNK("MAP_CHUNK"),
		MAP_CHUNK_BULK("MAP_CHUNK_BULK"),
		MOUNT("MOUNT"),
		MULTI_BLOCK_CHANGE("MULTI_BLOCK_CHANGE"),
		NAMED_ENTITY_SPAWN("NAMED_ENTITY_SPAWN"),
		NAMED_SOUND_EFFECT("NAMED_SOUND_EFFECT"),
		NBT_QUERY("NBT_QUERY"),
		OPEN_BOOK("OPEN_BOOK"),
		OPEN_SIGN_EDITOR("OPEN_SIGN_EDITOR"),
		OPEN_SIGN_ENTITY("OPEN_SIGN_ENTITY"),
		OPEN_WINDOW("OPEN_WINDOW"),
		OPEN_WINDOW_HORSE("OPEN_WINDOW_HORSE"),
		OPEN_WINDOW_MERCHANT("OPEN_WINDOW_MERCHANT"),
		PING("PING"),
		PLAYER_INFO("PLAYER_INFO"),
		PLAYER_INFO_REMOVE("PLAYER_INFO_REMOVE"),
		PLAYER_LIST_HEADER_FOOTER("PLAYER_LIST_HEADER_FOOTER"),
		POSITION("POSITION"),
		RECIPES("RECIPES"),
		RECIPE_UPDATE("RECIPE_UPDATE"),
		REL_ENTITY_MOVE("REL_ENTITY_MOVE"),
		REL_ENTITY_MOVE_LOOK("REL_ENTITY_MOVE_LOOK"),
		REMOVE_ENTITY_EFFECT("REMOVE_ENTITY_EFFECT"),
		RESOURCE_PACK_SEND("RESOURCE_PACK_SEND"),
		RESPAWN("RESPAWN"),
		SCOREBOARD_DISPLAY_OBJECTIVE("SCOREBOARD_DISPLAY_OBJECTIVE"),
		SCOREBOARD_OBJECTIVE("SCOREBOARD_OBJECTIVE"),
		SCOREBOARD_SCORE("SCOREBOARD_SCORE"),
		SCOREBOARD_TEAM("SCOREBOARD_TEAM"),
		SELECT_ADVANCEMENT_TAB("SELECT_ADVANCEMENT_TAB"),
		SERVER_DIFFICULTY("SERVER_DIFFICULTY"),
		SET_BORDER_CENTER("SET_BORDER_CENTER"),
		SET_BORDER_LERP_SIZE("SET_BORDER_LERP_SIZE"),
		SET_BORDER_SIZE("SET_BORDER_SIZE"),
		SET_BORDER_WARNING_DELAY("SET_BORDER_WARNING_DELAY"),
		SET_BORDER_WARNING_DISTANCE("SET_BORDER_WARNING_DISTANCE"),
		SET_COMPRESSION("SET_COMPRESSION"),
		SET_COOLDOWN("SET_COOLDOWN"),
		SET_SLOT("SET_SLOT"),
		SPAWN_ENTITY("SPAWN_ENTITY"),
		SPAWN_ENTITY_EXPERIENCE_ORB("SPAWN_ENTITY_EXPERIENCE_ORB"),
		SPAWN_ENTITY_LIVING("SPAWN_ENTITY_LIVING"),
		SPAWN_ENTITY_PAINTING("SPAWN_ENTITY_PAINTING"),
		SPAWN_ENTITY_WEATHER("SPAWN_ENTITY_WEATHER"),
		SPAWN_POSITION("SPAWN_POSITION"),
		STATISTIC("STATISTIC"),
		STATISTICS("STATISTICS"),
		STOP_SOUND("STOP_SOUND"),
		TAB_COMPLETE_OUT("TAB_COMPLETE"),
		TAGS("TAGS"),
		TILE_ENTITY_DATA("TILE_ENTITY_DATA"),
		TITLE("TITLE"),
		@Deprecated
		TRANSACTION("TRANSACTION"),
		UNLOAD_CHUNK("UNLOAD_CHUNK"),
		UPDATE_ATTRIBUTES("UPDATE_ATTRIBUTES"),
		UPDATE_ENTITY_NBT("UPDATE_ENTITY_NBT"),
		UPDATE_HEALTH("UPDATE_HEALTH"),
		UPDATE_SIGN("UPDATE_SIGN"),
		UPDATE_TIME("UPDATE_TIME"),
		USE_BED("USE_BED"),
		VEHICLE_MOVE("VEHICLE_MOVE"),
		VIEW_CENTRE("VIEW_CENTRE"),
		VIEW_DISTANCE("VIEW_DISTANCE"),
		WINDOW_DATA("WINDOW_DATA"),
		WINDOW_ITEMS("WINDOW_ITEMS"),
		WORLD_BORDER("WORLD_BORDER"),
		WORLD_EVENT("WORLD_EVENT"),
		WORLD_PARTICLES("WORLD_PARTICLES"),

		;

		private final String lookupName;

		Server(String lookupName) {
			this.lookupName = lookupName;
		}

		public String lookupName() {
			return lookupName;
		}
	}
}
